version: "3"
services:
  mongodb:
    image: bitnami/mongodb:5.0
    ports:
      - 27017:27017

    environment:
      - ALLOW_EMPTY_PASSWORD=true
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=replicaset
  minio:
    image: bitnami/minio:2022.5.8
    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      - MINIO_ROOT_USER=admin123
      - MINIO_ROOT_PASSWORD=admin123
      - MINIO_DEFAULT_BUCKETS=parrhesia
  
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
